---
- hosts: scanners
  become: yes
  vars_files:
    - variables.yml
  tasks:
    - name: Create compile dirs
      file:
        path: /tmp/gvm
        state: directory
        mode: '0755'
    - name: Download OSPD tar.gz
      get_url:
        url:  https://github.com/greenbone/ospd/archive/v{{ospd_version}}.tar.gz
        dest: /tmp/gvm/ospd.tar.gz
    - name: Download OSPD-openvas tar.gz
      get_url:
        url:  https://github.com/greenbone/ospd-openvas/archive/v{{ospd_openvas_version}}.tar.gz
        dest: /tmp/gvm/ospd-openvas.tar.gz
    - name: Extract OSPD
      unarchive:
        src: /tmp/gvm/ospd.tar.gz
        dest: /tmp/gvm
        remote_src: yes
    - name: Extract OSPD-OpenVAS
      unarchive:
        src: /tmp/gvm/ospd-openvas.tar.gz
        dest: /tmp/gvm
        remote_src: yes
    - name: Initialize virtualenv
      command: 
        cmd: virtualenv --python python3.7  /opt/gvm/bin/ospd-scanner/
        creates: /opt/gvm/bin/ospd-scanner/bin/python
    - name: Install OSPD
      shell:
        cmd: . /opt/gvm/bin/ospd-scanner/bin/activate && pip3 install .
        chdir: /tmp/gvm/ospd-{{ospd_version}}
    - name: Install OSPD-OpenVAS
      shell:
        cmd: . /opt/gvm/bin/ospd-scanner/bin/activate && pip3 install .
        chdir: /tmp/gvm/ospd-openvas-{{ospd_openvas_version}}

