---
- hosts: scanners
  become: yes
  vars_files:
    - variables.yml
  tasks:
    - name: Create compile dirs
      file:
        path: /tmp/gvm
        state: directory
        owner: "{{remote_username}}"
        mode: '0755'
    - name: Download OpenVAS-SMB tar.gz
      get_url:
        url: https://github.com/greenbone/openvas-smb/archive/v{{openvas_smb_version}}.tar.gz
        dest: /tmp/gvm/openvas_smb_version.tar.gz
    - name: Extract OpenVAS-SMB
      unarchive:
        src: /tmp/gvm/openvas_smb_version.tar.gz
        dest: /tmp/gvm
        remote_src: yes
    - name: Create build dir
      file:
        path: /tmp/gvm/openvas-smb-{{openvas_smb_version}}/build
        state: directory
    - name: Build OpenVAS-SMB
      command: "{{ item }} chdir=/tmp/gvm/openvas-smb-{{openvas_smb_version}}/build"
      with_items:
        - cmake -DCMAKE_INSTALL_PREFIX=/opt/gvm ..
        - make
      environment:
        PKG_CONFIG_PATH: /opt/gvm/lib/pkgconfig:$PKG_CONFIG_PATH
    - name: Install OpenVAS-SMB
      make:
        chdir: /tmp/gvm/openvas-smb-{{openvas_smb_version}}/build
        target: install



