---
- hosts: logstash
  become: yes
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
    - name: Install curl
      apt:
        name: curl
        state: latest
    - name: Install java
      apt:
        name: default-jre
        state: latest
    - name: Add GPG key
      command: 
        cmd: apt-key adv --fetch-keys https://artifacts.elastic.co/GPG-KEY-elasticsearch 
    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: latest
    - name: Add Elastic repo
      copy: 
        src: ../../files/elastic-7.x.list
        dest: /etc/apt/sources.list.d/elastic-7.x.list
        owner: root
        group: root
        mode: '0644'
    - name: Update APT sources
      command: 
        cmd: apt update
    - name: Install Logstash
      apt:
        name: logstash
        state: latest
    - name: Copy Logstash syslog.conf pipeline
      copy: 
        src: ../../files/logstash_syslog_pipeline.conf
        dest: /etc/logstash/conf.d/syslog.conf
        owner: root
        group: root
        mode: '0644'
    - name: Copy rsyslog.conf
      copy: 
        src: ../../files/logstash_rsyslog.conf
        dest: /etc/rsyslog.conf
        owner: root
        group: root
        mode: '0644'
    - name: Copy vimrc
      copy: 
        src: /etc/vim/vimrc
        dest: /etc/vim/vimrc
        owner: root
        group: root
        mode: '0644'
    - name: Configure Logstash
      script:
        cmd: ../../scripts/configure-logstash.sh
        
